config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'top#index'
  get 'company' => 'top#company'
  get 'privacypolicy' => 'top#privacypolicy'
  get 'consume' => 'top#consume'
  get 'sitemap' => 'top#sitemap'
  get 'consume' => 'top#consume'
  get 'price' => 'top#price'
  
  get 'contact' => 'contact#index' #入力画面
  post 'contact/confirm' => 'contact#confirm' #確認画面
  post 'contact/thanks' => 'contact#thanks' #送信完了画面
  
  get 'estimate' => 'estimate#index'
  post 'estimate/confirm' => 'estimate#confirm' #確認画面
  post 'estimate/thanks' => 'estimate#thanks' #送信完了画面
  

  
  get 'submit' => 'submit#index'
  post 'submit/confirm' => 'submit#confirm' #確認画面
  post 'submit/thanks' => 'submit#thanks' #送信完了画面
  
  
  get 'guide' => 'guide#index'
  get 'cancel' => 'guide#cancel'
  get 'data' => 'guide#data'
  get 'faq' => 'guide#faq'
  get 'flow' => 'guide#flow'
  get 'inquiry' => 'guide#inquiry'
  get 'payment' => 'guide#payment'
  get 'dispatch' => 'guide#dispatch'

  get 'fc' => 'fc#index'
  get 'station' => 'fc#station'
  get 'briefing' => 'fc#briefing'
  get 'result' => 'fc#result'
  get 'success' => 'fc#success'
  get 'affiliation' => 'fc#affiliation'
  get 'contract' => 'fc#contract'
  get 'request' => 'fc#request'
  
  get 'printing' => 'printing#printing'
  get 'smile' => 'printing#smile'
  get 'card' => 'printing#card'
  get 'slip' => 'printing#slip'
  get 'postcard' => 'printing#postcard'
  get 'envelope' => 'printing#envelope'
  get 'flyer' => 'printing#flyer'
  get 'poster' => 'printing#poster'
  get 'brouchure' => 'printing#brouchure'
  get 'uniform' => 'printing#uniform'
  get 'stamp' => 'printing#stamp'
  get 'novelty' => 'printing#novelty'
  get 'telegram' => 'printing#telegram'
  
  get 'uniform' => 'printing#uniform'
  get 'apron' => 'printing#apron'
  get 'baby' => 'printing#baby'
  get 'cap' => 'printing#cap'
  get 'hoodie' => 'printing#hoodie'
  get 'polo' => 'printing#polo'
  get 'sweat' => 'printing#sweat'
  get 'tshirt' => 'printing#t-shirt'
  get 'tanktop' => 'printing#tank-top'
  
  get 'store' => 'store#index'
  get 'chugoku' => 'store#chugoku'
  get 'hokkaido' => 'store#hokkaido'
  get 'hokuriku' => 'store#hokuriku'
  get 'kanto' => 'store#kanto'
  get 'kinki' => 'store#kinki'
  get 'kyushu' => 'store#kyushu'
  get 'shikoku' => 'store#shikoku'
  get 'tohoku' => 'store#tohoku' 
  get 'tokai' => 'store#tokai'
 
  get 'adachinishi' => 'branch#adachinishi'
  get 'edogawa' => 'branch#edogawa'
  get 'oota' => 'branch#oota'
  get 'tokyokita' => 'branch#tokyokita'
  get 'hachinohe' => 'branch#hachinohe'
  get 'hikarigaoka' => 'branch#hikarigaoka'
  get 'kyotonakagyo' => 'branch#kyotonakagyo'
  get 'shiranuka' => 'branch#shiranuka'
  get 'takamatsunishi' => 'branch#takamatsunishi'  
  get 'tokushima' => 'branch#tokushima'
  get 'yokohamacyuou' => 'branch#yokohamacyuou'

  get 'promotion' => 'promotion#index'
  get 'dm' => 'promotion#dm'
  get 'homepage_' => 'promotion#homepage_'
  get 'mobile' => 'promotion#mobile'
  
  get 'member' => 'member#index'
  get 'member/etc'=> 'member#etc'
  get 'login' => 'login#index'
  
  
  get 'admin' => 'admin#index'
  
  

  # For details on the DSL available within this file, see http:' => '' => 'guides.rubyonrails.org' => 'routing.html
end

app/models/estimate.rb
class Estimate
  include ActiveModel::Model
 
  attr_accessor :paper1, :paper, :type, :color1, :color2, :size, :size0, :size01, :size02, :size3, :type, :check,  :size1, :size2, :amount, :deliver, :title, :body, :attachment, :sirname, :firstname, :sirname_kana, :firstname_kana, :company, :postcode1, :postcode2, :prefecture, :city, :town, :building, :tel, :fax, :email, :message
  # validates :sirname, :presence => {:message => '名前を入力してください'}
  # validates :firstname, :presence => {:message => '名前を入力してください'}
  # validates :sirname_kana, :presence => {:message => 'フリガナを入力してください'}
  # validates :firstname_kana, :presence => {:message => 'フリガナを入力してください'}
  # validates :postcode1, :presence => {:message => '郵便番号を入力してください'}
  # validates :postcode2, :presence => {:message => '郵便番号を入力してください'}
  # validates :prefecture, :presence => {:message => '都道府県を選択してください'}
  # validates :city, :presence => {:message => '市区町村を入力してください'}
  # validates :town, :presence => {:message => '町名・番地をを入力してください'} 
  # validates :tel, :presence => {:message => '電話番号を入力してください'} 
  # validates :tel, :presence => {:check => 'ご希望のご連絡方法をチェックしてください'} 
  # validates :email, :presence => {:message => 'メールアドレスを入力してください'}
  # validates :message, :presence => {:message => 'お問い合わせ内容を選択ください'} 
  
  def attachment_params # <= コレ追加
  params.require(:attachment).permit(:attachment)
  end
 
end

app/controllers/estimate_controller.rb
class EstimateController < ApplicationController
    layout 'top'
    
  def index
    # 入力画面を表示
    @estimate = Estimate.new
    render :action => 'index'
  end
 
def confirm
  check_params = params.permit(:num, {:check => []}, :hoge)
params.permit!
# 入力値のチェック
@estimate = Estimate.new(params[:estimate])


if @estimate.valid?
  # OK。確認画面を表示
  render :action => 'confirm'
else
  # NG。入力画面を再表示
  render :action => 'index'
end

 

def thanks
params.permit!
# メール送信
@estimate = Estimate.new(params[:estimate])
EstimateMailer.received_email(@estimate).deliver
# 完了画面を表示
render :action => 'thanks'
end

# private
print
  def estimate_params
    params.require(:estimate).permit(:paper1, :type, :paper2, :type, :check,  :size1, :size2, :amount, :deliver, :sirname, :firstname, :sirname_kana, :firstname_kana, :company, :postcode1, :postcode2, :prefecture, :city, :town, :building, :tel, :fax, :email, :message)

  
  end
end
end

app/views/estimate/confirm.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
 
<%= form_for @estimate, :url => estimate_thanks_path do |f| %>
  <table class="table">

    <tr><th>ご希望の印刷物</th>
      <td>
        <%= f.hidden_field :paper1 %>
        <%= @estimate.paper1 %>
        <%= @estimate.paper %>
        <%= f.hidden_field :paper %>

      </td>
    </tr>
    <tr><th>型番</th>
      <td>
        <%= f.hidden_field :type %>
        <%= @estimate.type %>
      </td>
    </tr>
    <tr><th>刷り色数: 表面</th>
      <td>
        <%= f.hidden_field :color1 %>
        <%= @estimate.color1 %>
      </td>
    </tr>   
    <tr><th>刷り色数: 裏面</th>   
      <td>
        <%= f.hidden_field :color2 %>
        <%= @estimate.color2 %>
      </td>
    </tr>
    <tr><th>用紙サイズ</th>
      <td>
        <%= f.hidden_field :size %>
        <%= @estimate.size %>
        <%= f.hidden_field :size0 %>
        <%= @estimate.size0 %> :
        <%= f.hidden_field :size01 %>
        <%= @estimate.size01 %> mm x 
        <%= f.hidden_field :size02 %>
        <%= @estimate.size02 %> mm
      </td>
    </tr>
    </tr>
    <tr> <th>必要数</th>
      <td>
        <%= f.hidden_field :amount %>
        <%= @estimate.amount %>
      </td>
    </tr>    
    <tr><th>納品納品日</th>
      <td>
        <%= f.hidden_field :deliver %>
        <%= @estimate.deliver %>
      </td>
    </tr>
    <tr><th>添付ファイル01</th>
      <td>
        <%= f.hidden_field :attachment %>
        <%= @estimate.attachment %>
      </td>
    </tr>    
    <tr><th>添付ファイル02</th>
      <td></td>
    </tr>    
    <tr><th>添付ファイル03</th>
      <td></td>
    </tr>
    
    <tr>
      <th>お名前</th>
      <td>
        <%= f.hidden_field :sirname %>
        <%= @estimate.sirname %>
        <%= f.hidden_field :firstname %>
        <%= @estimate.firstname %>
      </td>
    </tr>
      <th>フリガナ</th>
      <td>
        <%= f.hidden_field :sirname_kana %>
        <%= @estimate.sirname_kana %>
        <%= f.hidden_field :firstname_kana %>
        <%= @estimate.firstname_kana %>
      </td>
    </tr>
     <tr>
      <th>会社名・担当部署</th>
      <td>
        <%= f.hidden_field :company %>
        <%= @estimate.company %>
      </td>
    </tr> 
    <tr>
      <th>郵便番号</th>
      <td>
        <%= f.hidden_field :postcode1 %>
        <%= @estimate.postcode1 %>-
        <%= f.hidden_field :postcode2 %>
        <%= @estimate.postcode2 %>
      </td>
    </tr> 
    <tr>
      <th>都道府県</th>
      <td>
        <li>
        <%= @estimate.prefecture %>
        <%= f.hidden_field :prefecture %>
        </li>
      
      </td>
    </tr> 
    <tr>
      <th>市区町村</th>
      <td>
        <%= f.hidden_field :city %>
        <%= @estimate.city %>
      </td>
    </tr> 
    <tr>
      <th>町名・番地</th>
      <td>
        <%= f.hidden_field :town %>
        <%= @estimate.town %>
      </td>
    </tr> 
    <tr>
      <th>建物名</th>
      <td>
        <%= f.hidden_field :building %>
        <%= @estimate.building %>
      </td>
    </tr> 
    <tr>
      <th>TEL</th>
      <td>
        <%= f.hidden_field :tel %>
        <%= @estimate.tel %>
      </td>
    </tr> 
    <tr>
      <th>FAX</th>
      <td>
        <%= f.hidden_field :fax %>
        <%= @estimate.fax %>
      </td>
    </tr> 
    <tr>
      <th>Eメール</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @estimate.email %>
      </td>
    </tr> 
    <tr>
      <th>特記事項・必要要綱など</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@estimate.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'btn btn-primary' %>
<% end %>

app/views/estimate/index.html.erb
<!-- START MAIN -->
    <div id="main">
     <div id="breadcrumb-container">
      <div id="breadcrumb">
       <div id="breadcrumb-nav"><a href="/" title="HOME">HOME</a> &gt; お見積り依頼 </div>
      </div>
      <div id="userinfo">
       
      </div>
     </div>
     <article>
            <h1 class="title-estimate">お見積り依頼</h1>
      <p>下記フォームに必要事項を入力し、送信してください。<br>お客さまからいただいたご連絡先が間違っている場合や、システム障害などによりお返事できない場合がごく稀にございます。<br>万が一、資料が届かない場合は、お手数ですが、お電話またはFAXにてその旨をお問い合わせください。</p>

      <section>
       <h3 class="subtitle">お見積もり依頼フォーム</h3>
       <p class="red h">（*）は必須項目となります。</p>
        
      <%= form_for @estimate, :url => estimate_confirm_path do |f| %>     
        <% if @estimate.errors.any? %>
            <strong>入力内容にエラーがあります</strong>
            <ul>
              <% @estimate.errors.each do |attr, msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
        <% end %>
        
       
<!--<form action="https://www.printhakase.com/estimate.html" method="post" enctype="multipart/form-data" id="EstimateForm"><input type="hidden" name="_mode" value="conf" />-->
<table border="0" cellpadding="0" cellspacing="0" class="form">
 <tr>
  <th colspan="2" class="head"><strong>印刷物に関する情報を入力してください</strong></td>
 </tr>
 <tr>
  <th>ご希望の印刷物<span class="red">*</span></th>
  <td>
    <p class="radio01"><%= f.radio_button :paper1, "名刺・カード" %> 
    <%= f.label :paper1, "名刺・カード" %></p>
    <p class="radio01"><%= f.radio_button :paper1, "伝票" %> 
    <%= f.label :paper1, "伝票" %></p>
    <p class="radio01"><%= f.radio_button :paper1, "ハガキ印刷" %> 
    <%= f.label :paper1, "ハガキ印刷" %></p>
    <p class="radio01"><%= f.radio_button :paper1, "封筒" %> 
    <%= f.label :paper1, "封筒" %>
    <p class="radio01"><%= f.radio_button :paper1, "チラシ・フライヤー" %> 
    <%= f.label :paper1, "チラシ・フライヤー" %></p>
    <p class="radio01"><%= f.radio_button :paper1, "ポスター" %> 
    <%= f.label :paper1, "ポスター" %></p>
    <p class="radio01"><%= f.radio_button :paper1, "会社案内等" %> 
    <%= f.label :paper1, "会社案内等" %></p>
    <p class="radio01"><%= f.radio_button :paper1, "ユニフォーム各種" %> 
    <%= f.label :paper1, "ユニフォーム各種" %></p>
    <p class="radio01"><%= f.radio_button :paper1, "はんこ" %> 
    <%= f.label :paper1, "はんこ" %></p>
    <p class="radio01"><%= f.radio_button :paper1, "ノベルティ関連" %> 
    <%= f.label :paper1, "ノベルティ関連" %></p>
    <p class="radio01"><%= f.radio_button :paper1, "その他印刷" %> 
    <%= f.label :paper1, "その他印刷" %></p><br class="clear">
    <p class="radio1">その他印刷を選択した方は下記にご記入ください。</p>
    <%= f.text_field :paper %>

   <!--<p class="radio01"><label for="card"><input type="radio" name="paper1" value="名刺・カード" id="card" checked />名刺・カード</label></p>-->
   <!--<p class="radio01"><label for="slip"><input type="radio" name="paper1" value="伝票" id="slip" />伝票</label></p>-->
   <!--<p class="radio01"><label for="postcard"><input type="radio" name="paper1" value="ハガキ印刷" id="postcard" />ハガキ印刷</label></p>-->
   <!--<p class="radio01"><label for="envelope"><input type="radio" name="paper1" value="封筒" id="envelope" />封筒</label></p>-->
   <!--<p class="radio01"><label for="flier"><input type="radio" name="paper1" value="チラシ・フライヤー" id="flier" />チラシ・フライヤー</label></p>-->
   <!--<p class="radio01"><label for="poster"><input type="radio" name="paper1" value="ポスター" id="poster" />ポスター</label></p>-->
   <!--<p class="radio01"><label for="booklet"><input type="radio" name="paper1" value="会社案内等" id="booklet" />会社案内等</label></p>-->
   <!--<p class="radio01"><label for="uniform"><input type="radio" name="paper1" value="ユニフォーム各種" id="uniform" />ユニフォーム各種</label></p>-->
   <!--<p class="radio01"><label for="stamp"><input type="radio" name="paper1" value="はんこ" id="stamp" />はんこ</label></p>-->
   <!--<p class="radio01"><label for="novelty"><input type="radio" name="paper1" value="ノベルティ関連" id="novelty" />ノベルティ関連</label></p>-->
   <!--<p class="radio01"><label for="other"><input type="radio" name="paper1" value="その他印刷" id="other" />その他印刷</label></p><br class="clear">-->
   <!--<p class="ex">その他印刷を選択した方は下記にご記入ください。</p>-->
   <!--<input type="text" name="paper2" class="long">-->
   
  </td>
 </tr>
 <tr>
  <th>型番</th>
  <td>
    <%= f.text_field :type %>
    <!--<input type="text" name="type" class="short"></td>-->
 </tr>
 <tr>
  <th rowspan="2">刷り色数<span class="red">*</span></th>
  <td>
   <p class="radio02"> <%= f.label :color1, "表面：4色 = フルカラー　0色 = 印刷なし" %></p>
   <p class="radio02"><%= f.radio_button :color1, "4色" %> <%= f.label :color1, "4色" %></p>  
   <p class="radio02"><%= f.radio_button :color1, "2色" %> <%= f.label :color1, "2色" %></p>
   <p class="radio02"><%= f.radio_button :color1, "1色"  %> <%= f.label :color1, "1色" %></p>
   <p class="radio02"><%= f.radio_button :color1, "0色" %> <%= f.label :color1, "0色" %></p>
   <p class="radio02"><%= f.radio_button :color1, "紙媒体以外"%> <%= f.label :color1, "紙媒体以外" %></p>


   
   <!--<p>表面：&nbsp;<span class="gray">4色 = フルカラー　0色 = 印刷なし</span></p>-->
   <!--<p class="radio02"><label for="4c"><input type="radio" name="color1" value="4色" id="4c" checked />4色</label></p>-->
   <!--<p class="radio02"><label for="2c"><input type="radio" name="color1" value="2色" id="2c" />2色</label></p>-->
   <!--<p class="radio02"><label for="1c"><input type="radio" name="color1" value="1色" id="1c" />1色</label></p>-->
   <!--<p class="radio02"><label for="0c"><input type="radio" name="color1" value="0色" id="0c" />0色</label></p>-->
   <!--<p class="radio01"><label for="otherc"><input type="radio" name="color1" value="紙媒体以外" id="otherc" />紙媒体以外</label></p>-->
   
  </td>
 </tr>
 <tr>
  <td>
   <p class="radio02"> <%= f.label :color2, "裏面：4色 = フルカラー　0色 = 印刷なし" %></p>
   <p class="radio02"><%= f.radio_button :color2, "4色" %> <%= f.label :color2, "4色" %></p>  
   <p class="radio02"><%= f.radio_button :color2, "2色" %> <%= f.label :color2, "2色" %></p>
   <p class="radio02"><%= f.radio_button :color2, "1色" %> <%= f.label :color2, "1色" %></p>
   <p class="radio02"><%= f.radio_button :color2, "0色" %> <%= f.label :color2, "0色" %></p>
   <p class="radio02"><%= f.radio_button :color2, "紙媒体以外" %> <%= f.label :color2, "紙媒体以外" %></p>

   
   <!--<p>裏面：&nbsp;<span class="gray">4色 = フルカラー　0色 = 印刷なし</span>-->
   <!--<p class="radio02"><label for="4cb"><input type="radio" name="color2" value="4色" id="4cb" checked />4色</label></p>-->
   <!--<p class="radio02"><label for="2cb"><input type="radio" name="color2" value="2色" id="2cb" />2色</label></p>-->
   <!--<p class="radio02"><label for="1cb"><input type="radio" name="color2" value="1色" id="1cb" />1色</label></p>-->
   <!--<p class="radio02"><label for="0cb"><input type="radio" name="color2" value="0色" id="0cb" />0色</label></p>-->
   <!--<p class="radio01"><label for="othercb"><input type="radio" name="color2" value="紙媒体以外" id="othercb" />紙媒体以外</label></p>-->
   
  </td>
 </tr>
 <tr>
  <th>用紙サイズ<span class="red">*</span><br />複数サイズでの見積可</th>
  <td>
        <p class="radio02"> <%= f.radio_button :size, "名刺サイズ" %> <%= f.label :size, "名刺サイズ" %></p>
        <p class="radio02"> <%= f.radio_button :size, "官製はがき" %> <%= f.label :size, "官製はがき" %></p>
        <p class="radio02"> <%= f.radio_button :size, "名刺サイズ" %> <%= f.label :size, "名刺サイズ" %></p><br class="clear">
        
        <p class="radio02"> <%= f.radio_button :size, "A4" %> <%= f.label :size, "A4" %></p>
        <p class="radio02"> <%= f.radio_button :size, "A3" %> <%= f.label :size, "A3" %></p>
        <p class="radio02"> <%= f.radio_button :size, "A2" %> <%= f.label :size, "A2" %></p>
        <p class="radio02"> <%= f.radio_button :size, "A1" %> <%= f.label :size, "A1" %></p><br class="clear">
        
        <p class="radio02"> <%= f.radio_button :size, "B5" %> <%= f.label :size, "B5" %></p>
        <p class="radio02"> <%= f.radio_button :size, "B4" %> <%= f.label :size, "B4" %></p>
        <p class="radio02"> <%= f.radio_button :size, "B3" %> <%= f.label :size, "B3" %></p>
        <p class="radio02"> <%= f.radio_button :size, "B2" %> <%= f.label :size, "B2" %></p>
        <p class="radio02"> <%= f.radio_button :size, "B1" %> <%= f.label :size, "B1" %></p><br class="clear">
        
        <p class="radio02"> <%= f.radio_button :size0, "指定サイズ" %> <%= f.label :size0, "指定サイズ" %></p>
        <p><%= f.text_field :size01 %> mm × <%= f.text_field :size02 %> mm</p><br class="clear">
         
        <p class="radio02"> <%= f.radio_button :size, "紙媒体以外" %> <%= f.label :size, "紙媒体以外" %>
        
       
       
        
        
   <!--<p class="radio01"><label for="cardsize"><input type="checkbox" name="size[]" value="名刺サイズ " id="cardsize" />名刺サイズ</label></p>-->
   <!--<p class="radio01"><label for="postcardsize"><input type="checkbox" name="size[]" value="官製はがき " id="postcardsize" />官製はがき</label></p><br class="clear" />-->
   <!--<p class="radio02"><label for="A4"><input type="checkbox" name="size[]" value="A4 " id="A4" />A4</label></p>-->
   <!--<p class="radio02"><label for="A3"><input type="checkbox" name="size[]" value="A3 " id="A3" />A3</label></p>-->
   <!--<p class="radio02"><label for="A2"><input type="checkbox" name="size[]" value="A2 " id="A2" />A2</label></p>-->
   <!--<p class="radio02"><label for="A1"><input type="checkbox" name="size[]" value="A1 " id="A1" />A1</label></p><br class="clear">-->
   <!--<p class="radio02"><label for="B5"><input type="checkbox" name="size[]" value="B5 " id="B5" />B5</label></p>-->
   <!--<p class="radio02"><label for="B4"><input type="checkbox" name="size[]" value="B4 " id="B4" />B4</label></p>-->
   <!--<p class="radio02"><label for="B3"><input type="checkbox" name="size[]" value="B3 " id="B3" />B3</label></p>-->
   <!--<p class="radio02"><label for="B2"><input type="checkbox" name="size[]" value="B2 " id="B2" />B2</label></p>-->
   <!--<p class="radio02"><label for="B1"><input type="checkbox" name="size[]" value="B1 " id="B1" />B1</label></p><br class="clear">-->
   <!--<p><label for="specific"><input type="checkbox" name="size[]" value="指定サイズ" id="specific" />指定サイズ</label>-->
   <!--<input type="text" name="size1" class="veryshort" /> mm × <input type="text" name="size2" class="veryshort" /> mm<br class="clear">-->
   <!--<label for="othersize"><input type="checkbox" name="size[]" value="紙媒体以外 " id="othersize" />紙媒体以外</label>-->
   
  </td>
 </tr>
 <tr>
  <th>必要数<span class="red">*</span></th>
  <td>
      <%= f.check_box(:amount,{:multiple=>true},'指定サイズ',nil) %>
        <%= label_tag :amount,'' %>
        <%= f.text_field :amount %><br />記入例）1,000部、1,000枚など
   <!--<input type="text" name="amount" class="short"><br />記入例）1,000部、1,000枚など-->
  </td>
 </tr>
 <tr>
  <th>希望納品日<span class="red">*</span></th>
  <td>
    <%= f.check_box(:deliver,{:multiple=>true},'指定サイズ',nil) %>
        <%= label_tag :deliver,'' %>
        <%= f.text_field :deliver %><br />記入例）2017年01月01日、1週間以内など
  </td>
 </tr>
 <tr>
  <th>添付ファイル01<br />参考見本資料等</th>
  <td>
     <%= f.file_field :attachment %>
   <input type="file" name="file1" class="middle" /><br>
  <span class="red">※アップロードするファイルのファイル名は、すべて半角英数字でお願い致します。<br>※一度にアップロードできるのは50MBまでです。（複数個の場合、その合計）</span></td>
 </tr>
 <tr>
  <th>添付ファイル02<br />参考見本資料等</th>
  <td><input type="file" name="file2" class="middle" /></td>
 </tr>
 <tr>
  <th>添付ファイル03<br />参考見本資料等</th>
  <td><input type="file" name="file3" class="middle" /></td>
 </tr>
 <tr>
  <th colspan="2" class="head"><strong>お客様情報を入力してください</strong></td>
 </tr>
 <tr>
  <th>お名前<span class="red">*</span></th>
  <td>
    <%= f.text_field :sirname %>
    <%= f.text_field :firstname %>
  </td>
 </tr>
 <tr>
  <th>フリガナ<span class="red">*</span></th>
  <td>
    <%= f.text_field :sirname_kana %>
    <%= f.text_field :firstname_kana %>
  </td>
 </tr>
 <tr>
  <th>会社名・担当部署</th>
    <td>
    <%= f.text_field :company %>
    </td>
 </tr>
 <tr>
  <th>郵便番号<span class="red">*</span></th>
  <td>
   <%= f.text_field :postcode1 %>-<%= f.text_field :postcode2 %>
 </tr>
 <tr>
  <th>都道府県<span class="red">*</span></th>
  <td>
    <%= f.select :prefecture, grouped_options_for_select(Prefecture::SELECT_OPTIONS),  :prompt => "選択してください" %>
  
  </td>
 </tr>
 <tr>
  <th>市区町村<span class="red">*</span></th>
  <td>
   <%= f.text_field :city %>
  </td>
 </tr>
 <tr>
  <th>町名・番地<span class="red">*</span></th>
  <td>
   <%= f.text_field :town %>
  </td>
 </tr>
 <tr>
  <th>建物名</th>
 <td>
 <%= f.text_field :building %>
 </td>
 </tr>
 <tr>
  <th>TEL<span class="red">*</span></th>
  <td>
   <%= f.text_field :tel %>
  </td>
 </tr>
 <tr>
  <th>FAX</th>
   <td><%= f.text_field :fax %></td>
 </tr>
 <tr>
  <th>Eメール<span class="red">*</span></th>
  <td>
   <%= f.text_field :email %>
  </td>
 </tr>
 <tr>
  <th>特記事項・必要事項など</th>
  <td><%= f.text_area :message %></textarea>

    </td>
 </tr>
</table>
 <div id="button-container">
  <%= f.submit 'submit', class: 'confirm'  %>
 </div>
</form>

      </section>
     </article>
     <div id="pagetop"> 
      <a href="#">↑ページの先頭へ戻る</a> 
     </div>
    </div>
<% end %>

app/views/estimate/thanks.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
<p>
  お問い合わせいただきありがとうございました。
</p>