config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'top#index'
  get 'company' => 'top#company'
  get 'privacypolicy' => 'top#privacypolicy'
  get 'consume' => 'top#consume'
  get 'sitemap' => 'top#sitemap'
  get 'consume' => 'top#consume'
  get 'price' => 'top#price'
  
  get 'contact' => 'contact#index' #入力画面
  post 'contact/confirm' => 'contact#confirm' #確認画面
  post 'contact/thanks' => 'contact#thanks' #送信完了画面
  
  get 'estimate' => 'estimate#index'
  post 'estimate/confirm' => 'estimate#confirm' #確認画面
  post 'estimate/thanks' => 'estimate#thanks' #送信完了画面
  

  
  get 'submit' => 'submit#index'
  post 'submit/confirm' => 'submit#confirm' #確認画面
  post 'submit/thanks' => 'submit#thanks' #送信完了画面
  
  
  get 'guide' => 'guide#index'
  get 'cancel' => 'guide#cancel'
  get 'data' => 'guide#data'
  get 'faq' => 'guide#faq'
  get 'flow' => 'guide#flow'
  get 'inquiry' => 'guide#inquiry'
  get 'payment' => 'guide#payment'
  get 'dispatch' => 'guide#dispatch'

  get 'fc' => 'fc#index'
  get 'station' => 'fc#station'
  get 'briefing' => 'fc#briefing'
  get 'result' => 'fc#result'
  get 'success' => 'fc#success'
  get 'affiliation' => 'fc#affiliation'
  get 'contract' => 'fc#contract'
  get 'request' => 'fc#request'
  
  get 'printing' => 'printing#printing'
  get 'smile' => 'printing#smile'
  get 'card' => 'printing#card'
  get 'slip' => 'printing#slip'
  get 'postcard' => 'printing#postcard'
  get 'envelope' => 'printing#envelope'
  get 'flyer' => 'printing#flyer'
  get 'poster' => 'printing#poster'
  get 'brouchure' => 'printing#brouchure'
  get 'uniform' => 'printing#uniform'
  get 'stamp' => 'printing#stamp'
  get 'novelty' => 'printing#novelty'
  get 'telegram' => 'printing#telegram'
  
  get 'uniform' => 'printing#uniform'
  get 'apron' => 'printing#apron'
  get 'baby' => 'printing#baby'
  get 'cap' => 'printing#cap'
  get 'hoodie' => 'printing#hoodie'
  get 'polo' => 'printing#polo'
  get 'sweat' => 'printing#sweat'
  get 'tshirt' => 'printing#t-shirt'
  get 'tanktop' => 'printing#tank-top'
  
  get 'store' => 'store#index'
  get 'chugoku' => 'store#chugoku'
  get 'hokkaido' => 'store#hokkaido'
  get 'hokuriku' => 'store#hokuriku'
  get 'kanto' => 'store#kanto'
  get 'kinki' => 'store#kinki'
  get 'kyushu' => 'store#kyushu'
  get 'shikoku' => 'store#shikoku'
  get 'tohoku' => 'store#tohoku' 
  get 'tokai' => 'store#tokai'
 
  get 'adachinishi' => 'branch#adachinishi'
  get 'edogawa' => 'branch#edogawa'
  get 'oota' => 'branch#oota'
  get 'tokyokita' => 'branch#tokyokita'
  get 'hachinohe' => 'branch#hachinohe'
  get 'hikarigaoka' => 'branch#hikarigaoka'
  get 'kyotonakagyo' => 'branch#kyotonakagyo'
  get 'shiranuka' => 'branch#shiranuka'
  get 'takamatsunishi' => 'branch#takamatsunishi'  
  get 'tokushima' => 'branch#tokushima'
  get 'yokohamacyuou' => 'branch#yokohamacyuou'

  get 'promotion' => 'promotion#index'
  get 'dm' => 'promotion#dm'
  get 'homepage_' => 'promotion#homepage_'
  get 'mobile' => 'promotion#mobile'
  
  get 'member' => 'member#index'
  get 'member/etc'=> 'member#etc'
  get 'login' => 'login#index'
  
  
  get 'admin' => 'admin#index'
  
  

  # For details on the DSL available within this file, see http:' => '' => 'guides.rubyonrails.org' => 'routing.html
end

app/models/submit.rb
class Submit
  include ActiveModel::Model
 
  # attr_accessor :name, :email, :message
  attr_accessor :sirname, :firstname, :sirname_kana, :firstname_kana, :company, :postcode1, :postcode2, :prefecture, :city, :town, :building, :tel, :fax, :email, :check, :subject, :message
 
  validates :sirname, :presence => {:message => '名前を入力してください'}
  validates :firstname, :presence => {:message => '名前を入力してください'}
  validates :sirname_kana, :presence => {:message => 'フリガナを入力してください'}
  validates :firstname_kana, :presence => {:message => 'フリガナを入力してください'}
  validates :postcode1, :presence => {:message => '郵便番号を入力してください'}
  validates :postcode2, :presence => {:message => '郵便番号を入力してください'}
  validates :prefecture, :presence => {:message => '都道府県を選択してください'}
  validates :city, :presence => {:message => '市区町村を入力してください'}
  validates :town, :presence => {:message => '町名・番地をを入力してください'} 
  validates :tel, :presence => {:message => '電話番号を入力してください'} 
  validates :tel, :presence => {:check => 'ご希望のご連絡方法をチェックしてください'} 
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
  validates :subject, :presence => {:message => 'お問い合わせ種別を選択ください'} 
  validates :message, :presence => {:message => 'お問い合わせ内容を選択ください'} 

end

app/controllers/submit_controller.rb
class SubmitController < ApplicationController
    layout 'top'
    
def index
    # 入力画面を表示
    @submit = Submit.new
    render :action => 'index'
end
 
def confirm
    check_params = params.permit(:num, {:check => []}, :hoge)
    params.permit!
    # 入力値のチェック
    @submit = submit.new(params[:submit])


if @submit.valid?
  # OK。確認画面を表示
  render :action => 'confirm'
else
  # NG。入力画面を再表示
  render :action => 'index'
end

 

def thanks
    params.permit!
    # メール送信
    @submit = submit.new(params[:submit])
    SubmitMailer.received_email(@submit).deliver
    # 完了画面を表示
    render :action => 'thanks'
end

# private
    print
      def submit_params
        params.require(:submit).permit(:sirname_kana, :firstname_kana, :postcode1, :postcode2, :prefecture, :city, :town, :town, :tel, :check, :subject, :email, :message)
    
      
      end
    end
end

app/views/submit/confirm.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
 
<%= form_for @submit, :url =>submit_thanks_path do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :sirname %>
        <%= @submit.sirname %>
        <%= f.hidden_field :firstname %>
        <%= @submit.firstname %>
      </td>
    </tr>
      <th>フリガナ</th>
      <td>
        <%= f.hidden_field :sirname_kana %>
        <%= @submit.sirname_kana %>
        <%= f.hidden_field :firstname_kana %>
        <%= @submit.firstname_kana %>
      </td>
    </tr>
     <tr>
      <th>会社名・担当部署</th>
      <td>
        <%= f.hidden_field :company %>
        <%= @submit.company %>
      </td>
    </tr> <tr>
      <th>郵便番号</th>
      <td>
        <%= f.hidden_field :postcode1 %>
        <%= @submit.postcode1 %>-
        <%= f.hidden_field :postcode2 %>
        <%= @submit.postcode2 %>
      </td>
    </tr> <tr>
      <th>都道府県</th>
      <td>
        <li><%= @submit.prefecture %><%= f.hidden_field :prefecture %></li>
      
      </td>
    </tr> <tr>
      <th>市区町村</th>
      <td>
        <%= f.hidden_field :city %>
        <%= @submit.city %>
      </td>
    </tr> <tr>
      <th>町名・番地</th>
      <td>
        <%= f.hidden_field :town %>
        <%= @submit.town %>
      </td>
    </tr> <tr>
      <th>建物名</th>
      <td>
        <%= f.hidden_field :building %>
        <%= @submit.building %>
      </td>
    </tr> <tr>
      <th>TEL</th>
      <td>
        <%= f.hidden_field :tel %>
        <%= @submit.tel %>
      </td>
    </tr> <tr>
      <th>FAX</th>
      <td>
        <%= f.hidden_field :fax %>
        <%= @submit.fax %>
      </td>
    </tr> <tr>
      <th>Eメール</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @submit.email %>
      </td>
    </tr> <tr>
      <th>ご希望の連絡方法</th>
      <td>
        <%= f.hidden_field :check %>
        <%= @submit.check .join(", ") %>

      </td>
    </tr>
    <tr>
      <th>お問い合わせ種別</th>
      <td>
        <%= f.hidden_field :subject %>
        <%= simple_format(@submit.subject) %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@submit.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'btn btn-primary' %>
<% end %>

app/views/submit/index.html.erb
<!-- START MAIN -->
    <div id="main">
     <div id="breadcrumb-container">
      <div id="breadcrumb">
       <div id="breadcrumb-nav"><a href="/" title="HOME">HOME</a> &gt;  データ入稿</div>
      </div>
      <div id="userinfo">
       
      </div>
     </div>
     <article>
            <h1 class="title-submit">データ入稿</h1>
      <p>下記フォームに必要事項を入力し、送信してください。<br>お客さまからいただいたご連絡先が間違っている場合や、システム障害などによりお返事できない場合がごく稀にございます。<br>万が一、資料が届かない場合は、お手数ですが、お電話またはFAXにてその旨をお問い合わせください。</p>

      <section>
       <h3 class="subtitle">データ入稿フォーム</h3>
       <p class="red h">（*）は必須項目となります。</p>
          
      <%= form_for @submit, :url => submit_confirm_path do |f| %>
        <% if @submit.errors.any? %>
         <div class="alert alert-danger" role="alert">
           <strong>入力内容にエラーがあります</strong>
           <ul>
             <% @submit.errors.each do |attr, msg| %>
               <li><%= msg %></li>
         <% end %>
           </ul>
         </div>
      <% end %> 
       

<table border="0" cellpadding="0" cellspacing="0" class="form">
 <tr>
  <th>お名前<span class="red">*</span></th>
  <td>
    <%= f.text_field :sirname %>
    <%= f.text_field :firstname %>
  </td>
 </tr>
 <tr>
  <th>フリガナ<span class="red">*</span></th>
  <td>
    <%= f.text_field :sirname_kana %>
    <%= f.text_field :firstname_kana %>
  </td>
 </tr>
 <tr>
  <th>会社名・担当部署</th>
    <td>
    <%= f.text_field :company %>
      </td>
 </tr>
 <tr>
  <th>郵便番号<span class="red">*</span></th>
  <td>
   <%= f.text_field :postcode1 %>-<%= f.text_field :postcode2 %>
   </td>
 </tr>
 <tr>
  <th>都道府県<span class="red">*</span></th>
  <td>
    <%= f.select :prefecture, grouped_options_for_select(Prefecture::SELECT_OPTIONS),  :prompt => "選択してください" %>
  </td>
 </tr>
 <tr>
  <th>市区町村<span class="red">*</span></th>
  <td>
   <%= f.text_field :city %>
   
  </td>
 </tr>
 <tr>
  <th>町名・番地<span class="red">*</span></th>
  <td>
   <%= f.text_field :town %>
   
  </td>
 </tr>
 <tr>
  <th>建物名</th>
  <td><%= f.text_field :building %></td>
 </tr>
 <tr>
  <th>TEL<span class="red">*</span></th>
  <td>
   <%= f.text_field :tel %>
   
  </td>
 </tr>
 <tr>
  <th>FAX</th>
  <td><%= f.text_field :fax %></td>
 </tr>
 <tr>
  <th>Eメール<span class="red">*</span></th>
  <td>
   <%= f.text_field :email %>
   
  </td>
 </tr>
 <tr>
  <th>ご希望の連絡方法<span class="red">*</span></th>
  <td>
     <%= f.check_box(:check,{:multiple=>true}, 'TEL',nil) %>
     <%= label_tag :check,'TEL' %>
     <%= f.check_box(:check,{:multiple=>true},'FAX',nil) %>
     <%= label_tag :check,'FAX' %>
     <%= f.check_box(:check,{:multiple=>true},'Email',nil) %>
     <%= label_tag :check,'Email' %>

  </td>
 </tr>
 <tr>
  <th>ファイル1<span class="red">*</span></th>
  <td>
   <input type="file" name="file1" class="txt2"><br>
   <span class="red">※アップロードするファイルのファイル名は、すべて半角英数字でお願い致します。<br>※一度にアップロードできるのは50MBまでです。（複数個の場合、その合計）</span>
　</td>
 </tr>
 <tr>
  <th>ファイル2</th>
  <td>
   <input type="file" name="file2" class="txt2">
　</td>
 </tr>
 <tr>
  <th>ファイル3</th>
  <td>
   <input type="file" name="file3" class="txt2">
　</td>
 </tr>
 <tr>
  <th>特記事項・必要事項など</th>
  <td><textarea name="message" wrap="hard"></textarea></td>
 </tr>
</table>
<div id="button-container">
  　　  <%= f.submit 'submit', class: 'confirm'  %>

</form>

      </section>
     </article>
     <div id="pagetop"> 
      <a href="#">↑ページの先頭へ戻る</a> 
     </div>
    </div>
<!-- END MAIN -->
<% end %>

app/views/submit/thanks.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
<p>
  お問い合わせいただきありがとうございました。
</p>