config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'top#index'
  get 'company' => 'top#company'
  get 'privacypolicy' => 'top#privacypolicy'
  get 'consume' => 'top#consume'
  get 'sitemap' => 'top#sitemap'
  get 'consume' => 'top#consume'
  get 'price' => 'top#price'
  
  get 'contact' => 'contact#index' #入力画面
  post 'contact/confirm' => 'contact#confirm' #確認画面
  post 'contact/thanks' => 'contact#thanks' #送信完了画面
  
  get 'estimate' => 'estimate#index'
  post 'estimate/confirm' => 'estimate#confirm' #確認画面
  post 'estimate/thanks' => 'estimate#thanks' #送信完了画面
  

  
  get 'submit' => 'submit#index'
  post 'submit/confirm' => 'submit#confirm' #確認画面
  post 'submit/thanks' => 'submit#thanks' #送信完了画面
  
  
  get 'guide' => 'guide#index'
  get 'cancel' => 'guide#cancel'
  get 'data' => 'guide#data'
  get 'faq' => 'guide#faq'
  get 'flow' => 'guide#flow'
  get 'inquiry' => 'guide#inquiry'
  get 'payment' => 'guide#payment'
  get 'dispatch' => 'guide#dispatch'

  get 'fc' => 'fc#index'
  get 'station' => 'fc#station'
  get 'briefing' => 'fc#briefing'
  get 'result' => 'fc#result'
  get 'success' => 'fc#success'
  get 'affiliation' => 'fc#affiliation'
  get 'contract' => 'fc#contract'
  get 'request' => 'fc#request'
  
  get 'printing' => 'printing#printing'
  get 'smile' => 'printing#smile'
  get 'card' => 'printing#card'
  get 'slip' => 'printing#slip'
  get 'postcard' => 'printing#postcard'
  get 'envelope' => 'printing#envelope'
  get 'flyer' => 'printing#flyer'
  get 'poster' => 'printing#poster'
  get 'brouchure' => 'printing#brouchure'
  get 'uniform' => 'printing#uniform'
  get 'stamp' => 'printing#stamp'
  get 'novelty' => 'printing#novelty'
  get 'telegram' => 'printing#telegram'
  
  get 'uniform' => 'printing#uniform'
  get 'apron' => 'printing#apron'
  get 'baby' => 'printing#baby'
  get 'cap' => 'printing#cap'
  get 'hoodie' => 'printing#hoodie'
  get 'polo' => 'printing#polo'
  get 'sweat' => 'printing#sweat'
  get 'tshirt' => 'printing#t-shirt'
  get 'tanktop' => 'printing#tank-top'
  
  get 'store' => 'store#index'
  get 'chugoku' => 'store#chugoku'
  get 'hokkaido' => 'store#hokkaido'
  get 'hokuriku' => 'store#hokuriku'
  get 'kanto' => 'store#kanto'
  get 'kinki' => 'store#kinki'
  get 'kyushu' => 'store#kyushu'
  get 'shikoku' => 'store#shikoku'
  get 'tohoku' => 'store#tohoku' 
  get 'tokai' => 'store#tokai'
 
  get 'adachinishi' => 'branch#adachinishi'
  get 'edogawa' => 'branch#edogawa'
  get 'oota' => 'branch#oota'
  get 'tokyokita' => 'branch#tokyokita'
  get 'hachinohe' => 'branch#hachinohe'
  get 'hikarigaoka' => 'branch#hikarigaoka'
  get 'kyotonakagyo' => 'branch#kyotonakagyo'
  get 'shiranuka' => 'branch#shiranuka'
  get 'takamatsunishi' => 'branch#takamatsunishi'  
  get 'tokushima' => 'branch#tokushima'
  get 'yokohamacyuou' => 'branch#yokohamacyuou'

  get 'promotion' => 'promotion#index'
  get 'dm' => 'promotion#dm'
  get 'homepage_' => 'promotion#homepage_'
  get 'mobile' => 'promotion#mobile'
  
  get 'member' => 'member#index'
  get 'member/etc'=> 'member#etc'
  get 'login' => 'login#index'
  
  
  get 'admin' => 'admin#index'
  
  

  # For details on the DSL available within this file, see http:' => '' => 'guides.rubyonrails.org' => 'routing.html
end

app/models/contact.rb
class Contact
  include ActiveModel::Model
 
  # attr_accessor :name, :email, :message
  attr_accessor :sirname, :firstname, :sirname_kana, :firstname_kana, :company, :postcode1, :postcode2, :prefecture, :city, :town, :building, :tel, :fax, :email, :check, :subject, :message
 
  validates :sirname, :presence => {:message => '名前を入力してください'}
  validates :firstname, :presence => {:message => '名前を入力してください'}
  validates :sirname_kana, :presence => {:message => 'フリガナを入力してください'}
  validates :firstname_kana, :presence => {:message => 'フリガナを入力してください'}
  validates :postcode1, :presence => {:message => '郵便番号を入力してください'}
  validates :postcode2, :presence => {:message => '郵便番号を入力してください'}
  validates :prefecture, :presence => {:message => '都道府県を選択してください'}
  validates :city, :presence => {:message => '市区町村を入力してください'}
  validates :town, :presence => {:message => '町名・番地をを入力してください'} 
  validates :tel, :presence => {:message => '電話番号を入力してください'} 
  validates :email, :presence => {:message => 'メールアドレスを入力してください'}
  validates :subject, :presence => {:message => 'お問い合わせ種別を選択ください'} 
  validates :message, :presence => {:message => 'お問い合わせ内容を選択ください'} 

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
    layout 'top'
    
  def index
    @contact = Contact.new
    render :action => 'index'
  end
 
def confirm
  check_params = params.permit(:num, {:check => []}, :hoge )
  params.permit!
  # 入力値のチェック
  @contact = Contact.new(params[:contact])


if @contact.valid?
  # OK。確認画面を表示
  render :action => 'confirm'
else
  # NG。入力画面を再表示
  render :action => 'index'
end

 

def thanks
  params.permit!
  # メール送信
  @contact = Contact.new(params[:contact])
  ContactMailer.received_email(@contact).deliver
  # 完了画面を表示
  render :action => 'thanks'
end

# private
print
  def contact_params
    params.require(:contact).permit(:sirname_kana, :firstname_kana, :postcode1, :postcode2, :prefecture, :city, :town, :town, :tel, :check, :subject, :email, :message)

  
  end
end
end

app/views/contact/confirm.html.1.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
 
<%= form_for @contact, :url => contact_thanks_path do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :sirname %>
        <%= @contact.sirname %>
        <%= f.hidden_field :firstname %>
        <%= @contact.firstname %>
      </td>
    </tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :sirname_kana %>
        <%= @contact.sirname %>
        <%= f.hidden_field :firstname_kana %>
        <%= @contact.firstname %>
      </td>
    </tr>
     <tr>
      <th>会社名・担当部署</th>
      <td>
        <%= f.hidden_field :company %>
        <%= @contact.company %>
      </td>
    </tr> <tr>
      <th>郵便番号</th>
      <td>
        <%= f.hidden_field :postcode1 %>
        <%= @contact.postcode1 %>
        <%= f.hidden_field :postcode2 %>
        <%= @contact.postcode2 %>
      </td>
    </tr> <tr>
      <th>都道府県</th>
      <td>
        <%= f.hidden_field :prefecture %>
        <%= @contact.prefecture %>
      </td>
    </tr> <tr>
      <th>市区町村</th>
      <td>
        <%= f.hidden_field :city %>
        <%= @contact.city %>
      </td>
    </tr> <tr>
      <th>町名・番地</th>
      <td>
        <%= f.hidden_field :town %>
        <%= @contact.ntowname %>
      </td>
    </tr> <tr>
      <th>建物名</th>
      <td>
        <%= f.hidden_field :building %>
        <%= @contact.building %>
      </td>
    </tr> <tr>
      <th>TEL</th>
      <td>
        <%= f.hidden_field :tel %>
        <%= @contact.tel %>
      </td>
    </tr> <tr>
      <th>FAX</th>
      <td>
        <%= f.hidden_field :fax %>
        <%= @contact.fax %>
      </td>
    </tr> <tr>
      <th>Eメール</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @contact.email %>
      </td>
    </tr> <tr>
      <th>ご希望の連絡方法</th>
      <td>
        <%= f.hidden_field :check %>
        <%= @contact.check %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ種別</th>
      <td>
        <%= f.hidden_field :prefecture %>
        <%= simple_format(@contact.prefecture) %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@contact.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'btn btn-primary' %>
<% end %>

app/views/contact/confirm.html.erb
<div class="page-header">
  <h1>お問い合わせ</h1>
</div>
 
<%= form_for @contact, :url => contact_thanks_path do |f| %>
  <table class="table">
    <tr>
      <th>名前</th>
      <td>
        <%= f.hidden_field :sirname %>
        <%= @contact.sirname %>
        <%= f.hidden_field :firstname %>
        <%= @contact.firstname %>
      </td>
    </tr>
      <th>フリガナ</th>
      <td>
        <%= f.hidden_field :sirname_kana %>
        <%= @contact.sirname_kana %>
        <%= f.hidden_field :firstname_kana %>
        <%= @contact.firstname_kana %>
      </td>
    </tr>
     <tr>
      <th>会社名・担当部署</th>
      <td>
        <%= f.hidden_field :company %>
        <%= @contact.company %>
      </td>
    </tr> <tr>
      <th>郵便番号</th>
      <td>
        <%= f.hidden_field :postcode1 %>
        <%= @contact.postcode1 %>-
        <%= f.hidden_field :postcode2 %>
        <%= @contact.postcode2 %>
      </td>
    </tr> <tr>
      <th>都道府県</th>
      <td>
        <li><%= @contact.prefecture %><%= f.hidden_field :prefecture %></li>
      
      </td>
    </tr> <tr>
      <th>市区町村</th>
      <td>
        <%= f.hidden_field :city %>
        <%= @contact.city %>
      </td>
    </tr> <tr>
      <th>町名・番地</th>
      <td>
        <%= f.hidden_field :town %>
        <%= @contact.town %>
      </td>
    </tr> <tr>
      <th>建物名</th>
      <td>
        <%= f.hidden_field :building %>
        <%= @contact.building %>
      </td>
    </tr> <tr>
      <th>TEL</th>
      <td>
        <%= f.hidden_field :tel %>
        <%= @contact.tel %>
      </td>
    </tr> <tr>
      <th>FAX</th>
      <td>
        <%= f.hidden_field :fax %>
        <%= @contact.fax %>
      </td>
    </tr> <tr>
      <th>Eメール</th>
      <td>
        <%= f.hidden_field :email %>
        <%= @contact.email %>
      </td>
    </tr> <tr>
      <th>ご希望の連絡方法</th>
      <td>
        <%= f.hidden_field :check %>
        <%= @contact.check .join(", ") %>

      </td>
    </tr>
    <tr>
      <th>お問い合わせ種別</th>
      <td>
        <%= f.hidden_field :subject %>
        <%= simple_format(@contact.subject) %>
      </td>
    </tr>
    <tr>
      <th>お問い合わせ内容</th>
      <td>
        <%= f.hidden_field :message %>
        <%= simple_format(@contact.message) %>
      </td>
    </tr>
  </table>
  <%= f.submit '送信', :class => 'btn btn-primary' %>
<% end %>

app/views/contact/index.html.erb
<!-- START MAIN -->
    <div id="main">
     <div id="breadcrumb-container">
      <div id="breadcrumb">
       <div id="breadcrumb-nav"><a href="/" title="HOME">HOME</a> &gt;  お問い合わせ</div>
      </div>
      <div id="userinfo">
       
      </div>
     </div>
     <article>
            <h1 class="title-contact">お問い合わせ</h1>
      <p>下記フォームに必要事項を入力し、送信してください。<br>お客さまからいただいたご連絡先が間違っている場合や、システム障害などによりお返事できない場合がごく稀にございます。<br>万が一、資料が届かない場合は、お手数ですが、お電話またはFAXにてその旨をお問い合わせください。</p>

      <section>
       <h3 class="subtitle">お問い合わせフォーム</h3>
       <p class="red h">（*）は必須項目となります。</p>
       
       <%= form_for @contact, :url => contact_confirm_path do |f| %>
        <% if @contact.errors.any? %>
         <div class="alert alert-danger" role="alert">
           <strong>入力内容にエラーがあります</strong>
           <ul>
             <% @contact.errors.each do |attr, msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
        <% end %>
       
<!--<form action="https://www.printhakase.com/contact.html" method="post" id="ContactForm"><input type="hidden" name="_mode" value="conf" />-->
<table border="0" cellpadding="0" cellspacing="0" class="form">
 <tr>
  <th>お名前<span class="red">*</span></th>
  <td>
    <%= f.text_field :sirname %>
    <%= f.text_field :firstname %>
   <!--<input name="sirname" class="txt1" type="text">-->
   <!--<input name="firstname" class="txt1" type="text">-->
   
  </td>
 </tr>
 <tr>
  <th>フリガナ<span class="red">*</span></th>

  <td>
    <%= f.text_field :sirname_kana %>
    <%= f.text_field :firstname_kana %>
   <!--<input name="sirname_kana" class="txt1" type="text"> <input name="firstname_kana" class="txt1" type="text">-->
   
  </td>
 </tr>
 <tr>

  <th>会社名・担当部署</th>
    <td>
    <%= f.text_field :company %>
      </td>
  <!--<td><input name="company" class="txt2" type="text"></td>-->
 </tr>
 <tr>
  <th>郵便番号<span class="red">*</span></th>
  <td>
   <%= f.text_field :postcode1 %>-<%= f.text_field :postcode2 %>
   <!--<input name="postcode1" class="postcode" type="text">-<input name="postcode2" class="postcode" type="text">-->
   </td>

 </tr>
 <tr>
  <th>都道府県<span class="red">*</span></th>
  <td>
 <%= f.select :prefecture, [["Railsの基礎", "rails_base"], ["Rubyの基礎", "ruby_base"]],  :prompt => "選択してください" %>
   
   
  </td>
 </tr>
 <tr>
  <th>市区町村<span class="red">*</span></th>
  <td>
   <!--<input name="city" class="txt2" type="text">-->
   <%= f.text_field :city %>
  </td>
 </tr>
 <tr>
  <th>町名・番地<span class="red">*</span></th>
  <td>
   <!--<input name="town" class="txt2" type="text">-->
   <%= f.text_field :town %>
  </td>
 </tr>
 <tr>
  <th>建物名</th>
  <!--<td><input name="building" class="txt2" type="text"></td>-->
  <td>
 <%= f.text_field :building %>
 </td>
 </tr>
 <tr>
  <th>TEL<span class="red">*</span></th>
  <td>
   <!--<input name="tel" class="txt1" type="text">-->
   <%= f.text_field :tel %>
  </td>
 </tr>
 <tr>
  <th>FAX</th>
  <td><%= f.text_field :fax %></td>
  <!--<input name="fax" class="txt1" type="text">-->
 </tr>
 <tr>
  <th>Eメール<span class="red">*</span></th>
  <td>
   <!--<input name="email" class="txt2" type="text">-->
   <%= f.text_field :email %>
   
  </td>
 </tr>
 <tr>
  <th>ご希望の連絡方法<span class="red">*</span></th>
  <td>
   
  <input type="checkbox" name="check[]" value="iPhone">アイフォン
  <input type="checkbox" name="check[]" value="Android">アンドロイド
  <input type="checkbox" name="check[]" value="WindowsPhone">ウィンドウズフォン
  </td>
 </tr>
 <tr>
  <th>お問い合わせ種別<span class="red">*</span></th>
  <td>
  <%= f.select :subject, [["Railsの基礎", "rails_base"], ["Rubyの基礎", "ruby_base"]],  :prompt => "選択してください" %>

   
　</td>
 </tr>
 <tr>
  <th>お問い合わせ内容<span class="red">*</span></th>
  <td>
  <%= f.text_area :message %>
  </td>
 </tr>
</table>
<div id="button-container">
   <%= f.submit 'submit', class: 'confirm'  %>
   <!--<input type="submit" class="confirm" value="内容確認"></div>-->

</form>

      </section>
     </article>
     <div id="pagetop"> 
      <a href="#">↑ページの先頭へ戻る</a> 
     </div>
    </div>
<!-- END MAIN -->
<% end %>